// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvgi16IAIliCYh85AX3FZqg1Cr89vkIQ',
    appId: '1:156075817613:web:e15506e8b31111a508c0c4',
    messagingSenderId: '156075817613',
    projectId: 'cmsc-23-mini-project',
    authDomain: 'cmsc-23-mini-project.firebaseapp.com',
    storageBucket: 'cmsc-23-mini-project.appspot.com',
    measurementId: 'G-6TT3C785VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7R4MHDm8ue_mheVqOafg7DQRDW5QJySM',
    appId: '1:156075817613:android:d8385cffabf2c8c808c0c4',
    messagingSenderId: '156075817613',
    projectId: 'cmsc-23-mini-project',
    storageBucket: 'cmsc-23-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAW7sU0rPR2uAexcrH8gADQenD8UmI02U',
    appId: '1:156075817613:ios:71e6dc8a5738a0dd08c0c4',
    messagingSenderId: '156075817613',
    projectId: 'cmsc-23-mini-project',
    storageBucket: 'cmsc-23-mini-project.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAW7sU0rPR2uAexcrH8gADQenD8UmI02U',
    appId: '1:156075817613:ios:71e6dc8a5738a0dd08c0c4',
    messagingSenderId: '156075817613',
    projectId: 'cmsc-23-mini-project',
    storageBucket: 'cmsc-23-mini-project.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );

}